### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by abuassar** [vasyliv/ngx-virtual-swiper#1]
this is a very promising tool, but the RTL support is not there yet.

I'm looking forward to use it in my app once you make it work with right-to-left direction.

thanks

ps. to test rtl you may set `<html dir="rtl">`

**Comment by vasyliv** [comment]
@abuassar thanks for your testing, I'm going to implement this feature, but now I've got a lot of work with my projects. I hope I'll have time next month.

**Comment by vasyliv** [comment]
@abuassar the bug is fixed, please try version 0.2.0

**Comment by abuassar** [comment]
awesome!

thanks alot
